import Head from "next/head"
import Navbar from "../components/Navbar/Navbar"
import styles from "../styles/Home.module.scss"
import Typewriter from 'react-simple-typewriter'
import 'react-simple-typewriter/dist/index.css'

export default function Home() {
  return (
    <div className={styles.wrapper}>
      <div className={styles.container}>
        <Head>
          <title>Dimitri Rose</title>
          <meta name='description' content='Generated by create next app' />
          {/*/<link rel='icon' href='/favicon.ico' />*/}
        </Head>

        <Navbar />
        <div className={styles.body}>
            <h1 className={styles.body__header}>Dimitri Rose:</h1>
            <Typewriter
                loop
                cursor
                cursorStyle='_'
                typeSpeed={70}
                deleteSpeed={50}
                delaySpeed={1000}
                words={['Engineer', 'Designer', 'Mathematician']}
            />
        </div>
      </div>
    </div>
  )
}
