import Head from "next/head"
import styles from "../styles/Home.module.css"
import Navbar from "../components/Navbar/Navbar"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dimitri Rose</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />
    </div>
  )
}
